import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Auto-generated sidebars based on docs folder structure
const sidebars: SidebarsConfig = {
  userGuideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user-guide',
    },
  ],
  agentDevelopersSidebar: [
    {
      type: 'autogenerated',
      dirName: 'agent-developers',
    },
  ],
  platformDevelopersSidebar: [
    {
      type: 'autogenerated',
      dirName: 'platform-developers',
    },
  ],
};

export default sidebars;
